### ISSUE TITLE
Incorrect import

### ISSUE THREAD

**Issue by techtana0x** [quiknode-labs/qn-guide-examples#56]
import should be `import { ArbBot, SwapToken } from './bot';` instead of `import { ArbBot, SwapToken } from './index';`

https://github.com/quiknode-labs/qn-guide-examples/blob/af8f2b3d920c527a244ac670b73513512882cc89/solana/jupiter-bot/index.ts#L2

**Comment by TheOratorEse** [comment]
Agreed 👍🏽  maybe an honest error there

**Comment by amilz** [comment]
This appears to have been corrected, see:
https://github.com/quiknode-labs/qn-guide-examples/blob/ceacd298c3732284db48378975a7ddabd772b8a9/solana/jupiter-bot/index.ts#L2
